### ISSUE TITLE
Messages in the app seem to be missing from web UI

### ISSUE THREAD

**Issue by DavidHCrane** [PortablePixels/ClinicRoomAuth#9]
Melissa posted a message to the clinic room at 21:52. At 23:30 (when both screenshots were taken) her message does not seem to be visible in the web UI

## In-app
![image](https://user-images.githubusercontent.com/94664/75606192-36fed300-5ae2-11ea-8dd5-287cb52f24e6.png)

## Web UI
![image](https://user-images.githubusercontent.com/94664/75606200-4a11a300-5ae2-11ea-8687-34a99601a2b3.png)

**Comment by McLeanAdam** [comment]
@DavidHCrane, was that message visible to other users? Is this happening a lot?

<img width="1172" alt="Screenshot 2020-03-06 at 13 15 01" src="https://user-images.githubusercontent.com/46320820/76086722-94949300-5fac-11ea-81b1-4adb81a41b04.png">

The message is present in the history, so it was definitely sent from the device side.
